### ISSUE TITLE
Nova CLI tool for creating packages

### ISSUE THREAD

**Issue by alexbowers** [tightenco/nova-package-development#11]
I feel it would be useful for there to be a nova CLI tool that creates a package for you, offering you options to fill in as you go, and some prefilled ones that never change (eg. vendor).

What are other peoples thoughts on this? useful, or not worth the effort?

**Comment by dillingham** [comment]
As someone who’s released a few packages already, can you identify some paint points and things you think it should automate?

Here is one for larave packages for reference 
https://github.com/Jeroen-G/laravel-packager/

**Comment by alexbowers** [comment]
The pain points for me so far have been:

- Having to find the Spatie git URL every time for a new package to clone into a new folder.
- Doing the find replace (not too bad, but not the best experience. Most of it never changes for me)
- Removing the nova references in the composer.json (relative path etc).
- Removing the .circleci stuff
- Removing the tests folders
- Removing the files i dont use every time - Sometimes i use resources, sometimes i use http controllers, but not always for all of them.
- Remembering to remove the original .git dir to create my own

Thats just off the top of my head.

**Comment by alexbowers** [comment]
OK, i've built this. https://packagist.org/packages/alexbowers/nova-cli
