### ISSUE TITLE
Nova Import Manager

### ISSUE THREAD

**Issue by dillingham** [tightenco/nova-package-development#12]

**Comment by patrickbrouwers** [comment]
Challenge accepted ;)

Will be added to https://github.com/Maatwebsite/Laravel-Nova-Excel after Laravel Excel 3.1 is finished and released.

Will contain all the goodies 3.1 will have (batch inserts, chunk-reading, queued etc.)

**Comment by dillingham** [comment]
@patrickbrouwers 🚀 that would be huge! 

I feel like importing and exporting are going to be fundamental to a lot of nova apps.

1. How would you imagine relationship associations going?
2. Do you envision a "import template" download, like export example
3. Would you use nova's [action log](https://nova.laravel.com/docs/1.0/actions/defining-actions.html#action-log) or make a Import resource to store success / failed, export of failed, copy of attempted file etc
4. Lastly, is it weird that Im this excited about imports haha

**Comment by niladam** [comment]
@patrickbrouwers any news on this -- since 3.1 has been released ? It'd be great to have this ability in your nova package :)

**Comment by patrickbrouwers** [comment]
Haven’t gotten around to it. But we need it for a future project, so might come soon

**Comment by niladam** [comment]
@patrickbrouwers I'm really looking forward to this!:D

**Comment by Jeroenvanderholst** [comment]
@patrickbrouwers , I really like this idea. Have you had time yet?

**Comment by patrickbrouwers** [comment]
Not yet. If it’s of importance to someone we can prioritize it; see laravel-excel.com for the options.

**Comment by dillingham** [comment]
I might release my import code soon 👍

**Comment by simonhamp** [comment]
I've been working on [a little something](https://novapackages.com/packages/simonhamp/laravel-nova-csv-import)

**Comment by dillingham** [comment]
@simonhamp that looks perfect

**Comment by niladam** [comment]
@simonhamp whoa, nice one!:)

**Comment by maherelgamil** [comment]
@simonhamp Awesome :)
