### ISSUE TITLE
Nova Date Filter Package

### ISSUE THREAD

**Issue by dillingham** [tightenco/nova-package-development#17]

**Comment by dillingham** [comment]
https://github.com/dillingham/nova-relative-dates

Currently working on this package

**Comment by beliolfa** [comment]
Just published this package 

https://novapackages.com/packages/64robots/nova-date-filter

Hope it helps!

**Comment by dillingham** [comment]
@disitec awesome 🚀 Great example of using custom components in the filter

Any plans to support updated_at or custom date columns?

**Comment by disitec** [comment]
You can use this with every column in your table just apply the scope as usual
