### ISSUE TITLE
Nova Unique Field Package

### ISSUE THREAD

**Issue by dillingham** [tightenco/nova-package-development#19]

**Comment by dillingham** [comment]
Haven’t tested but looks promising 
https://novapackages.com/packages/epartment/nova-unique-ajax-field

**Comment by unxsist** [comment]
@dillingham  I made that package based on your package idea, if you miss anything, let me know!

**Comment by dillingham** [comment]
@unxsist awesome 😊 I think it’s well thought out. Allowing the choosing delay times and trigger events were a smart move. 

My feedback is maybe removing the namespaces from the readme demos so it’s cleaner, maybe show it first without the editable options. You could show how simple it is, Unique::make(‘Email’); then in a second section maybe “Optional Configurations”. 

Also maybe possibly Unique instead of UniqueAjax. All the fields in nova are one word, except DateTime, I think it would just feel a bit more native. I can’t think of a way unique would work without ajax the way you accomplished it, so I think you’re ok to tuck the implementation detail behind the scenes a bit.  

But that feedback is just to help in adoption, I think it looks great! Awesome! Totally something nova users will benefit from!

**Comment by unxsist** [comment]
@dillingham Thanks for your pull request and for your feedback! Really appreciate it. I kinda like `Unique` more too, but thought it would be confusing compared to the default Nova validation rules. Since it's a new package, I will make the change this weekend 👍

**Comment by dillingham** [comment]
@unxsist my pleasure, thanks for making this package! Excited to use it haha

Yeah I didnt think of that point, valid. I think it will be ok though

![unique](https://user-images.githubusercontent.com/29180903/45558051-f5ef0200-b80c-11e8-8bca-ea0398468869.PNG)

**Comment by unxsist** [comment]
I've renamed the field based on your feedback. I have to agree, it's more clean :)

**Comment by dillingham** [comment]
@unxsist wonderful! don't forget to compile :) `npm run prod` currently no dist folder

Also if on windows setting `mix.setPublicPath('dist')` prevents getting stuck at 95%

**Comment by dillingham** [comment]
@mattstauffer also launched
