### ISSUE TITLE
Smarter TextArea field

### ISSUE THREAD

**Issue by vootrunner** [tightenco/nova-package-development#20]
A package that acts as a normal textarea field but displays contents on the detail screen with an optional threshold for either the number of lines or characters to display before showing the 'click to view all' link.

Handy for actually displaying the contents of a textarea at a glance.

**Comment by nsaumini** [comment]
@vootrunner I have created a nova package called [ellipsis-textarea](https://novapackages.com/packages/saumini/ellipsis-textarea) which you can used to display n no. of characters in index view. No change in detail view.

**Comment by vootrunner** [comment]
Fantastic! Thanks!
