### ISSUE TITLE
Nova Quick Create Package

### ISSUE THREAD

**Issue by dillingham** [tightenco/nova-package-development#21]

**Comment by dillingham** [comment]
IN PROGRESS

![ba2acb2975974ebba87f7ebffb8b9806](https://user-images.githubusercontent.com/29180903/45583000-f7114500-b887-11e8-9297-c2865c61cef0.gif)

**Comment by dillingham** [comment]
![its-a-good-idea](https://user-images.githubusercontent.com/29180903/45794529-2dbed500-bc65-11e8-9526-63112dc83230.png)

I made this package just have no idea how to recommend implementing it

```
@include('nova-quick-create::dropdown')
```

I don't want to suggest users override the layout so early in development for this
Also can't add it to vendor/nova/partials/user because that's wrapped in a dropdown

Any suggestions?

**Comment by Kristories** [comment]
Awesome idea. You can use `artisan nova:asset` and use JavaScript to add :heavy_plus_sign: menu before user menu.

It would be nice if users could display their resource menu.

**Comment by dillingham** [comment]
@Kristories thanks! And thanks for the idea, I see how to finish this now :)

**Comment by bradydan** [comment]
Following 👍
