### ISSUE TITLE
Nova changelog

### ISSUE THREAD

**Issue by mattstauffer** [tightenco/nova-package-development#27]
This issue is here for me to test a feature, but imagine this were a card describing a package that shows the full Nova changelog (a feature I'm already working on adding to our tightenco/nova-releases package).

**Comment by mattstauffer** [comment]
I accept this challenge! I'm going to do this package, and therefore have added the `challenge-accepted` label to the idea that some other person who's definitely not me came up with.

**Comment by tnorthcutt** [comment]
![well-alright-jason-sudeikis](https://user-images.githubusercontent.com/796639/45320403-c8017900-b4ff-11e8-9c6a-a42126ad25af.gif)

**Comment by mattstauffer** [comment]
Closing because it's now a real thing: https://github.com/tightenco/nova-releases

But I still would welcome any more lovely GIFs (pronounced with a hard "g", like the G in Geitz) anyone wants to share.

**Comment by tnorthcutt** [comment]
> pronounced with a hard "g", like the G in Geitz

![gif image](https://user-images.githubusercontent.com/796639/45335572-3e709c00-b53d-11e8-82c7-2a09a606a1d4.gif)

**Comment by samanthamichele7** [comment]
![correct](https://media.giphy.com/media/GN27mINv3YjFm/giphy.gif)
