### ISSUE TITLE
More flexibility with UI

### ISSUE THREAD

**Issue by coding-sunshine** [tightenco/nova-package-development#28]
I know the theme made for Nova is amazing but, it would be great if people can make their own theme, not just CSS/JS but whole structure for themselves, as I can see a lot of great features built-in nova, but as an agency, we build a lot of CMS to manage client's request which even client and at times their customers have access to, no doubt with proper ACL, a lot of customers come to us with their own custom UI they want to build, right now in such scenarios, we have to build 2 CMS, one client and customer facing and one internal for development.

**Comment by alexbowers** [comment]
You can write a package that overrides all of the core files, so this is already do-able.

An example of how to override the files is here:

https://github.com/alexbowers/nova-multiple-dashboard/blob/master/src/ToolServiceProvider.php#L21

https://github.com/alexbowers/nova-multiple-dashboard/blob/master/resources/views/nova-overrides/dashboard/navigation.blade.php

This is overriding the sidebar Dashboard view, but there are several other views you can override to change the layout fundamentally.
