### ISSUE TITLE
Nova Create Child Relationship Package

### ISSUE THREAD

**Issue by julianpoma** [tightenco/nova-package-development#29]
The idea of this package is to let you create a new resource and many "child dependent" ones, on a single action. For example, we may have an Invoice that consists on many Invoice Items. 

```
** Invoice.php

public function items()
{
   return $this->hasMany(InvoiceItem::class);
}
```

```
** InvoiceItem.php

public function invoice()
{
   return $this->belongsTo(Invoice::class);
}
```

When creating a new Invoice, you should be able to add as many "items rows" as you want, and then save the corresponding data on in its own tables (invoices_table and invoice_items_table).

EDIT:
This is a gif of what I am looking for. It doesn't have to have those fancy total_price calcs, nor support complex input types: just basic ones like strings, numbers or a boolean.

![image](https://i.imgur.com/ImdYrrg.gif)

**Comment by cerelli** [comment]
Related to #9

**Comment by dillingham** [comment]
This is already possible by defining nova relationships.

**Comment by julianpoma** [comment]
@dillingham explain how?

**Comment by dillingham** [comment]
Provided you set up the relationships within nova, on the detail page of a invoice you would have a interface for items and the ability to create items accordingly. Maybe not exactly the user experience you’re hoping for tailored very specifically for invoices, but it’s capable. 

https://nova.laravel.com/docs/1.0/resources/relationships.html

**Comment by cerelli** [comment]
???
In the same page?
I want to create one page for spatie/laravel-permission.

![screenshot_20180910_154443](https://user-images.githubusercontent.com/6558535/45301309-f8054800-b510-11e8-9c70-27f47d45ba52.png)

**Comment by julianpoma** [comment]
@dillingham I already know that, and that the reason why I am posting this here. It's a matter of improving the UX and do things quickly.

![image](https://i.imgur.com/ImdYrrg.gif)

**Comment by dillingham** [comment]
Well they package has been created already. 
Using that package as a demo
https://novapackages.com/packages/vyuldashev/nova-permission
You can easily see what I am describing 
Which is the user detail page with role & permission on it.

**Comment by dillingham** [comment]
Oh I see what you mean. Cool 👍

**Comment by dillingham** [comment]
Doesn’t support relationships yet but this package has a really similar behavior but stores as json 

https://novapackages.com/packages/64robots/nova-row

**Comment by ovvessem** [comment]
Really like the idea of creating the parent and child in one page!

**Comment by voidgraphics** [comment]
Yessssssssss we need this

**Comment by dillingham** [comment]
https://novapackages.com/packages/yassi/nova-nested-form
Would work for this purpose considering some style differences

**Comment by dineshbabu03** [comment]
> The idea of this package is to let you create a new resource and many "child dependent" ones, on a single action. For example, we may have an Invoice that consists on many Invoice Items.
> 
> ```
> ** Invoice.php
> 
> public function items()
> {
>    return $this->hasMany(InvoiceItem::class);
> }
> ```
> 
> ```
> ** InvoiceItem.php
> 
> public function invoice()
> {
>    return $this->belongsTo(Invoice::class);
> }
> ```
> 
> When creating a new Invoice, you should be able to add as many "items rows" as you want, and then save the corresponding data on in its own tables (invoices_table and invoice_items_table).
> 
> EDIT:
> This is a gif of what I am looking for. It doesn't have to have those fancy total_price calcs, nor support complex input types: just basic ones like strings, numbers or a boolean.
> 
> ![image](https://camo.githubusercontent.com/bda10804f331f6e3f45aba73c4db69dfa234ca5c/68747470733a2f2f692e696d6775722e636f6d2f496d64597272672e676966)

Hello Julian,

Could please explain me how to create the invoice form design like in the above. Thanks
