### ISSUE TITLE
Dev tools in Nova when developing a package

### ISSUE THREAD

**Issue by mattstauffer** [tightenco/nova-package-development#3]
I *think* we found that copying `webpack.mix.js.dist` into `webpack.mix.js` in my Nova install, then running `npm install && npm run dev`, was supposed to be enough to get Nova's Vue in dev mode so I could then use the Vue dev tools, but I'm not 100% sure. I'm going to go re-try it later, but has anyone else run into this issue where you're writing a package and trying to debug it and you can't use the Vue dev tools?

**Comment by sidis405** [comment]
The inspection has been disabled by default. This forbids devtools from looking into it.
I had a run at it (including compiling nova on dev an so on) but to no effect.

Then i found two little flag disabled by default that did the trick. Put it in your `tool.js` like so:

```js
Nova.booting((Vue, router) => {

    Vue.config.devtools = true

    router.addRoutes([
        {...}
    ])
})
```

And Voilà

![screen shot 2018-08-31 at 11 37 28 pm](https://user-images.githubusercontent.com/844961/44937071-c86b7880-ad77-11e8-955a-6cd2b1b518a1.png)

Hope this helps :)

**Comment by sidis405** [comment]
I wasn't aware of it. Handy :) https://vuejs.org/v2/api/?#devtools
