### ISSUE TITLE
Nova Resource fields generator

### ISSUE THREAD

**Issue by akiyamaSM** [tightenco/nova-package-development#34]
A Laravel Nova packages that will help you to generate the fields from your Model easily.
Doc & Examples in the github repo.

https://github.com/akiyamaSM/nova-resource-maker

**Comment by alexbowers** [comment]
I think any announced packages should be kept to novapackages.com, and any issues stemming from them be closed, to keep the issues list clean.

Thoughts?

**Comment by mattstauffer** [comment]
@alexbowers I agree--that's why I originally closed it. I think that's wise. :)
