### ISSUE TITLE
Nova Relationship Sum Field Package

### ISSUE THREAD

**Issue by dillingham** [tightenco/nova-package-development#35]

**Comment by PrafullaKumarSahu** [comment]
@dillingham  is there any field/package or any way for this, that will set the value of total after making a calculation may be a sum, multiplication, custom mathematical expression or eloquent methods?

**Comment by dillingham** [comment]
@PrafullaKumarSahu You can do some stuff with laravel accessors and use $appends = [‘accessorName’] on your model to insure it’s accessible to nova and output the generated property as a text field

**Comment by PrafullaKumarSahu** [comment]
@dillingham that will only work to display, I am asking about something like, you have three fields price, quantity, and total as soon as you are making changes to price field or quantity field, it should reflect on total and you can submit all three fields,  is there any field/package like that?

**Comment by dillingham** [comment]
@PrafullaKumarSahu

You would use observers / resource events
https://nova.laravel.com/docs/1.0/resources/#resource-events

Save the value when saving not displaying

Good luck!

**Comment by PrafullaKumarSahu** [comment]
@dillingham thank you.
