### ISSUE TITLE
Nova Welcome Screen Package

### ISSUE THREAD

**Issue by dillingham** [tightenco/nova-package-development#36]

**Comment by akiyamaSM** [comment]
Could you explain its use case precisely?
Where it should be showen? Every time or after the login?..

**Comment by dillingham** [comment]
@akiyamaSM perhaps...

- custom card named Welcome
- almost purely aesthetic
- Card needs absolute positioning 
- $content could be a view path or text
- Might store a cookie or session upon login
- Doesn't show if cookie or session var present
- Might require migration, `$user->welcomed = true`

`Welcome($content, $duration, $showCloseButton, $buttonText);` 

Could also set cookie per resource, check the url in cookie 
This would allow Welcome cards to be unique to the page
This could make it a sort of on boarding information splash page
