### ISSUE TITLE
Passport API Generator

### ISSUE THREAD

**Issue by ibourgeois** [tightenco/nova-package-development#37]
A Nova package that can use Resources to generate an API with Passport.

- Should include a Tool for global management
- Should include a Resource Tool to enable and configure API settings per Resource

**Comment by ibourgeois** [comment]
claim

**Comment by ibourgeois** [comment]
URL for the repository: https://github.com/devoption/nova-api-generator

It is currently set to private, but I will make it public after I push what I have up later

**Comment by dillingham** [comment]
@ibourgeois just a heads up, this was just released 

https://novapackages.com/packages/kristories/novassport

**Comment by ibourgeois** [comment]
thanks for the heads up! I will take a look and if it makes sense to do so create a PR on their repo to add this functionality. That being said, I am curious how/if they managed to solve the issues regarding passport authentication with both the users API as well as nova-api. I managed to get one or the other pretty easily but combining them required a ton of manual changes to install.

**Comment by ibourgeois** [comment]
Oh wow. this is just a tool to manage Passport. Not at all what I am working on. I am working on direct API access from your application to Nova resources. What I have allows you to create your models, Nova resources and migrations... then develop your front end without the need for a controller unless you need the added complexity...

**Comment by dillingham** [comment]
@ibourgeois oh ok! I saw passport and skimmed. I assumed api authentication management
I see what you're saying, so its to build your app spa style? Not offer an external api?
Sorry for the mix up haha

**Comment by Kristories** [comment]
@ibourgeois I am curious about this idea. What's on my mind (and what I'm looking for) is 3rd party API can be consumed by resource (index, show, edit, delete). If the resource manages the database, this package manages the API.

By the way, thank you for mentioning my project @dillingham.

**Comment by dillingham** [comment]
abandoned
