### ISSUE TITLE
Nova Repeater Blocks

### ISSUE THREAD

**Issue by crumb1e** [tightenco/nova-package-development#38]
A package that lets you add a new field on the create/edit page, and allows you to choose from a range of field types.

**Comment by dillingham** [comment]
@crumb1e reminds me of the [Flexible Content](https://www.advancedcustomfields.com/resources/flexible-content/) field type of ACF
Would be cool for sure, there is https://github.com/64robots/nova-row for "repeating"

**Comment by dillingham** [comment]
Also seems like this package may be related
https://github.com/64robots/nova-json/
The combo of displaying and capturing dynamic json generated fields and repeating them in the nova-row package. Only missing a dropdrown to select which field vs a “add row” button

**Comment by m2de** [comment]
We have a working implementation for this now but the documentation needs to be improved and we want to spend some more time on boilerplate stuff, but the repo is here for anyone who wants to follow progress. https://github.com/dewsign/nova-repeater-blocks

**Comment by dillingham** [comment]
https://github.com/dewsign/nova-repeater-blocks
https://novapackages.com/packages/fourstacks/nova-repeatable-fields
https://novapackages.com/packages/guillaumeferron/post-content
