### ISSUE TITLE
Error Page Viewer

### ISSUE THREAD

**Issue by davidpiesse** [tightenco/nova-package-development#39]
For when you want easy access to all your pages/responses when you hit a 404/500/503 etc.

**Comment by dillingham** [comment]
Related
- https://novapackages.com/packages/spatie/nova-tail-tool
- https://novapackages.com/packages/php-junior/nova-logs
- https://novapackages.com/packages/kabbouchi/nova-logs-tool

**Comment by dillingham** [comment]
https://novapackages.com/packages/mad-web/nova-telescope-link
