### ISSUE TITLE
Nova Creator Field Package

### ISSUE THREAD

**Issue by dillingham** [tightenco/nova-package-development#46]

**Comment by alexbowers** [comment]
This could probably be done as part of the BelongsTo with a macro.

This would work as `BelongsTo::make('User')->defaultTo(..)` and `BelongsTo::make('User')->defaultToMe()` or something.

This should be pretty easy to do

**Comment by dillingham** [comment]
@alexbowers yeah. I was picturing it making a behind the scenes model event 

Order resource > Creator::make('User')
Order::saving user_id = auth()->user()->id

Blog resource > Creator::make('Author')
Blog::saving author_id = auth()->user()->id

**Comment by MarceauKa** [comment]
This is my solution.

For example, my Post model belongs to an User model via `user_id`:
```php
public function getUserIdAttribute()
{
    return ! $this->exists && \Auth::check() ? \Auth::user()->id : null;
}
```
