### ISSUE TITLE
Nova Select or Create Package

### ISSUE THREAD

**Issue by dillingham** [tightenco/nova-package-development#47]

**Comment by dillingham** [comment]
```html
<modal class="modal" tabindex="-1" role="dialog" @modal-close="handleClose">

    <component :is="CreateResource" :resourceName="resourceName"></component>

</modal>
```

```js
import CreateResource from '@/views/Create';
import Modal from '@/components/Modal';
```

**Comment by beliolfa** [comment]
This has been added to NovaFields 0.2.0

https://github.com/64robots/nova-fields

![sept-25-2018 15-46-42](https://user-images.githubusercontent.com/12644599/46019290-0ab87900-c0dc-11e8-832e-c85b2b83bf86.gif)

**Comment by dillingham** [comment]
@disitec darn, wish I could use it externally lol 😢

**Comment by dillingham** [comment]
@disitec that looks great! Well executed 😄

**Comment by dillingham** [comment]
Does it load the js / css for all other fields if I just want to use that one?

**Comment by disitec** [comment]
The provider loads js for all the suite

**Comment by dillingham** [comment]
@disitec ok so this isnt a good package to use if you just want one of your fields

**Comment by dillingham** [comment]
Except I want to use nova's fields not your package. Just one of the fields

Maybe Ill just copy your code and release it standalone lol
And not force people to adopt your adaptation of a official Laravel product

**Comment by disitec** [comment]
We are not forcing to anything. Just trying to help. Why not making a pr and improving it? We could use another constructive language. Just wanted to use all te custom classes implementation. If we release it as separate project nova fields would also be a dependency. I thing the cost is minimal but we are here to hear your thoughts.

**Comment by dillingham** [comment]
I **strongly** disagree with replacing all nova fields with yours. 
I unfortunately don't get to use your **awesome** features because of it.

**Comment by voidfire** [comment]
I'd like to incorporate the same functionality for BelongsToMany fields @disitec

**Comment by PrafullaKumarSahu** [comment]
@dillingham any basic example for this?
