### ISSUE TITLE
Resource Filter Dropdown Reset Button

### ISSUE THREAD

**Issue by michaelchunn** [tightenco/nova-package-development#50]
When you have many filters on the index page for a resource it would be very nice to have a "reset" button on the filter dropdown to revert all filters to defaults or "-" (none selected).

**Comment by michaelchunn** [comment]
package-idea

**Comment by dillingham** [comment]
@michaelchunn I think that's a great idea! No one has made that suggestion on [nova-issues](https://github.com/laravel/nova-issues/issues?q=is%3Aissue+is%3Aopen+label%3Arequest) 
Might be a good request for a core feature 😄  Thoughts?

**Comment by dillingham** [comment]
There is mention of including this in core, closing for that reason.
