### ISSUE TITLE
Nova Relationship Selector

### ISSUE THREAD

**Issue by chescos** [tightenco/nova-package-development#54]
Instead of automatically loading all relationship tables on the details view, relationship names are added to a select menu that enables easy and fast navigation with loading on demand.

Relationships are not automatically loaded when the details view is loaded. Instead, a relationship is only loaded when it is selected through the select menu. Only the currently selected relationship table is displayed.

This package would have two main goals:

1. Significantly improve the loading time of the details view when the resource has 10+ relationships
2. Improve navigation through many relationships (avoid so much scrolling)

Example:

![example-gif](https://user-images.githubusercontent.com/12296880/46228365-292fa600-c362-11e8-83b8-15b57191f125.gif)

**Comment by dillingham** [comment]
Nice idea! Would need to a table beneath the details as a separate field component

![related](https://user-images.githubusercontent.com/29180903/46229081-549a9c80-c332-11e8-9df8-1d61545471e3.png)
 
```php
Related::make()->types([
    HasMany::make('Comments'),
    BelongsToMany::make('Accounts'),
    MorphMany::make('Activities'),
])
```

on dropdown change event change a dynamic component

```
<component :is="selectedComponent" :resourceName="selectedResource"></component>
```

**Comment by chescos** [comment]
@dillingham yes, that's exactly what I mean!

**Comment by dillingham** [comment]
https://github.com/eminiarts/nova-tabs

**Comment by bajramemini** [comment]
Hello 

https://github.com/eminiarts/nova-relationship-selector

As discussed with @dillingham in our tabs-package, I extracted it to its own package.

Still needs a bit of styling, but the functionality is there.

Regards
Bajram

**Comment by chescos** [comment]
@bajramemini thank you so much for putting that together, just tried it out and it works great! My `User` model has 27 relationships and finally, I can add them to my `User` Nova resource.

@dillingham thank you too for communicating with him to make this happen :)

**Comment by dillingham** [comment]
@bajramemini thanks again for contributing such a useful package!

@chescos no problem :)
