### ISSUE TITLE
Nova Filter Quick Box

### ISSUE THREAD

**Issue by phoenixg** [tightenco/nova-package-development#56]
![image](https://user-images.githubusercontent.com/990040/47058441-a3cc4280-d1f7-11e8-9159-81358df59404.png)

**Comment by dillingham** [comment]
Can you include details / explanation?

**Comment by phoenixg** [comment]
@dillingham The default filter is implemented as a select box, I want to display at the top of the result list, and display as multiple select boxes equivalent to every field of the model.

**Comment by dillingham** [comment]
@phoenixg here is the package you've described

https://novapackages.com/packages/philperusse/nova-column-filter

May not be the same layout, but is accomplished

**Comment by phoenixg** [comment]
@dillingham Yeah I've noticed that, but it still needs me to click the right icon and pop out some options,  
I just want to display directly above the resource table.

**Comment by dillingham** [comment]
> May not be the same layout, but is accomplished

Im aware it isn't identical to what you want. 
But filters in Nova are in the filters menu.

**Comment by phoenixg** [comment]
@dillingham Yeah, I think it may should be supported by Nova itself
