### ISSUE TITLE
Finding popular packages

### ISSUE THREAD

**Issue by ryanmortier** [tightenco/nova-package-development#6]
It would be awesome to be able to sort by how many stars the package has on GitHub.

**Comment by mattstauffer** [comment]
@ryanmortier The "popular" section on the home page is sorting based on GitHub stars and Packagist downloads. Is there something about that feature that isn't providing what you want? Are you wanting more than six?

**Comment by mattstauffer** [comment]
@ryanmortier Also--I think you may have intended this for the novapackages-issues repo, which is where we handle conversations around novapackages.com; this repo is about discussing the process of Nova package development.

**Comment by ryanmortier** [comment]
@mattstauffer I wasn't aware of that, thanks. Also you're right on your second part. Closing.

**Comment by ryanmortier** [comment]
But yes, more than 6 would be awesome too.
