### ISSUE TITLE
Read-Only Fields [package-idea]

### ISSUE THREAD

**Issue by aarondfrancis** [tightenco/nova-package-development#60]
https://github.com/laravel/nova-issues/issues/19

**Comment by alexbowers** [comment]
There is a PR upstream for this.

**Comment by dillingham** [comment]
https://github.com/laravel/nova-issues/issues/19#issuecomment-425206317

**Comment by aarondfrancis** [comment]
@dillingham You've just pointed me to the same issue that I referenced when opening this issue. 🤔

**Comment by dillingham** [comment]
read only fields exist now

**Comment by ehben83** [comment]
But it's only working on certain types of fields 😢 (Text, TextArea)

**Comment by dillingham** [comment]
@ehben83 if you're only concern is that they see the value, why does it need to be a select box for example?

**Comment by ehben83** [comment]
Well the use case is the following : 

1. I create a Post with a Date field 
2. Then, another User can update that Post but shouldn't be allowed to update that Date field (read-only on update and ideally only for him)

How would you manage that?

**Comment by dillingham** [comment]
@ehben83 I would use authorization 👍 
```php
Date::make('Published')->exceptOnForms(),

Date::make('Published')->onlyOnForms()->canSee(function(){
    return $this->author_id == auth()->id();
})
```

The first field to display the value regardless of auth user
