### ISSUE TITLE
Nova Charting Package

### ISSUE THREAD

**Issue by Otienoh** [tightenco/nova-package-development#61]
### About Issue
Nova provides metrics which is good enough for metrics we have now (except the bar metrics which looks not pleasing) but the challenge is using that as the main charting solution as is makes it hard for us to give more detail and context to the charts. We need to find a way to customize the metric to add more properties eg titles, Legends, X & Y axis, different types of charts scatter chart e.t.c.

### Things to do

- [ ] Find ways to extend/tweak the rendered view on the metrics eg increasing height.
- [ ] Integrate a laravel charting library to help us generate the charts and reuse more code. Some good examples I have seen are [Laravel Charts](https://charts.erik.cat/) and http://lavacharts.com
 
### Sample Example
![laravel5-chart-example-using-charts-package-example](https://user-images.githubusercontent.com/8632640/50457883-09634a80-0970-11e9-966e-c7b7b8c704ab.png)
![php-hhvm-graph-10](https://user-images.githubusercontent.com/8632640/50457884-09fbe100-0970-11e9-9df9-15f8c7d5e9c0.png)

**Comment by fabiobettiol** [comment]
Looking forward for it!

**Comment by cord** [comment]
https://github.com/ankane/vue-chartkick looks like a good start

**Comment by Otienoh** [comment]
Closing this because good options are available

1. https://novapackages.com/packages/kirschbaum-development/nova-chartjs
2. https://novapackages.com/packages/charts/nova-line-chart
3. https://novapackages.com/packages/cloudstudio/card-extended -  Can be used as well
