### ISSUE TITLE
Resource Index Inline Editing

### ISSUE THREAD

**Issue by Dontorpedo** [tightenco/nova-package-development#62]
A feature to make the ressource editable inline would be supercool..

like fieldoption ->editableOnIndex() or something..

some columns need to be editet quickly, opening, editing and saving is a bit waste of time if one wants to edit several ressources..

**Comment by dillingham** [comment]
A little animated inspiration
![inspiration](https://user-images.githubusercontent.com/29180903/51076199-42cfd180-1663-11e9-8fc5-d3a5a60bbf10.gif)

**Comment by dillingham** [comment]
![update](https://user-images.githubusercontent.com/29180903/51076258-2f713600-1664-11e9-9026-49ee5308b585.png)

**Comment by Dontorpedo** [comment]
i managed to make a inlineedit field but it works not very well XD

i tried to reuse the nova update routes, but when a field in the resource is set as required the update doesnt work..

it doesnt work either if there is relationship.. 

it doenst work with select and datefields.. and i lack of exprience to make it better.. :/

**Comment by dillingham** [comment]
@Dontorpedo maybe post the code in a gist and share and others can contribute thoughts, feedback, revisions etc. kudos for getting somewhere with it :)

**Comment by Dontorpedo** [comment]
ok, so its here.. 

https://gist.github.com/Dontorpedo/b77ba72fcf51a4e763c076a24d54dc8e

i used the click-outside directive.. so the field is updated on a click outside the field..

**Comment by dillingham** [comment]
@Dontorpedo I think that looks good.

For a package, you could just make macros each time you figure out a component.

```php
Text::macro('editable', function ($model) {
    return $this->useComponent('editable-text');
});

Select::macro('editable', function ($model) {
    return $this->useComponent('editable-select');
});
```
```php
Text::make('Email')->editable();
Select::make('Email')->editable()->options([]);
```

Would have to figure out validation though
Relationships could be down the road

**Comment by PhilippeDirx** [comment]
Will this be made into a package on https://novapackages.com/ ?
I need dis 👍

**Comment by Dontorpedo** [comment]
@dillingham 

thanks for suggestions, will work on it soon

@PhilippeDirx 

hi, yes but i think not very soon

**Comment by bradydan** [comment]
Following 👍

**Comment by Yelles** [comment]
would love that too !!! 👍

**Comment by markrassamni** [comment]
@Dontorpedo Could you add an option for inline boolean toggling as well?

**Comment by dillingham** [comment]
https://novapackages.com/packages/kirschbaum-development/nova-inline-select

https://novapackages.com/packages/wehaa/inline-field-update

**Comment by shineirvin** [comment]
@Dontorpedo Could you please add an option for inline boolean toggling ? it would be really helpful.

**Comment by markrassamni** [comment]
@shineirvin I just released a package for inline boolean toggling found [here.](https://github.com/markrassamni/inline-boolean)

**Comment by LiamKarlMitchell** [comment]
Any updated packages for v4?
