### ISSUE TITLE
[package-idea] Select field with Ajax request based on value of other field

### ISSUE THREAD

**Issue by cliffordjames** [tightenco/nova-package-development#64]
Background info:

I'm building an application for managing networks, devices, ips etc.

When a user adds a new IP to a device, he needs to select a network first, then an ajax request needs to be made to fetch all available IPs in that network.

What I'm aiming for is something like this:

```php
AjaxSelect::make('ip')->basedOn('Network')->endpoint('api_url')
```

**Comment by dillingham** [comment]
@cliffordjames done 🚀 https://github.com/dillingham/nova-ajax-select
