### ISSUE TITLE
Saved Passwords Fields

### ISSUE THREAD

**Issue by foreachphp** [tightenco/nova-package-development#68]
@package-idea
#package-idea

There should be a package where you can input passwords, where it stores the passwords encrypted into the database and where the user can view their passwords when clicked on the eye button next to the ******

So basically something like LastPass.com

**Comment by dillingham** [comment]
There is a Password::make('Password') field for general use cases

However, you can't reveal the password to a user because that would require storing it in plain text which is a huge no no.

**Comment by foreachphp** [comment]
What about if I would like to make a app for myself that stores the passwords I have, since I can't trust 3rd parties or don't like saving it in notepads.

Can't we crypt an input, decrypt if a button is clicked?

**Comment by dillingham** [comment]
this sounds like a personal issue 👍
