### ISSUE TITLE
Not committing dist

### ISSUE THREAD

**Issue by FatBoyXPC** [tightenco/nova-package-development#7]
I see people removing the `dist` directory from their package's `.gitignore` and the purist in me cringes. That said, as I'm building my own package currently, I've noticed that nova package javascript resources don't get handled by the "parent app" webpack config. Parent app here means the app that will be consuming the nova package.

I'm a total js noob - what sort of work needs to be done to resolve this?

**Comment by mattstauffer** [comment]
Yah, you have to remove dist from `.gitignore`; it's a known issue I think they plan to fix, but they're gonna fix it by removing it from the ignore file, not by making the parent projects build those files.

I think. :)

**Comment by FatBoyXPC** [comment]
I'm not such a fan if that's the fix, I think the parent should be doing all of the build. Curious what kind of js conflicts could crop up with the parent doing the full build vs each package building its own.
