### ISSUE TITLE
Nova JS dependencies pull core file

### ISSUE THREAD

**Issue by alexbowers** [tightenco/nova-package-development#8]
I was testing out my package, which uses one of the mixins that comes with Nova JS (HasCards.js).

The way that it is pulled in Nova JS examples is using:

```
import { HasCards } from 'laravel-nova';
```

however, you can pull in the file using:
```
import HasCards from 'laravel-nova/src/mixins/HasCards';
```

and it has a massive filesize saving.

Using the example 1 your export is 80kb larger than the second one. They both do exactly the same thing.

Worth documenting.

**Comment by alexbowers** [comment]
![image](https://user-images.githubusercontent.com/842974/45057884-cb73ab00-b08e-11e8-8a99-6e9044ffe729.png)

**Comment by OwenMelbz** [comment]
Is this just from the IDE? Or is it the actual output size?

Would be interesting to see if the editor is just sizing the file path, rather than the outfitted file

**Comment by alexbowers** [comment]
It is the actual output size too. Verified it with `yarn prod`

**Comment by beliolfa** [comment]
In my case. The build size using the destructuring option is `152K` and the other one `177K`. Do you know why?

```js
import {
  TogglesTrashed,
  PerformsSearches,
  HandlesValidationErrors
} from 'laravel-nova';
// import TogglesTrashed from 'laravel-nova/src/mixins/TogglesTrashed';
// import PerformsSearches from 'laravel-nova/src/mixins/PerformsSearches';
// import HandlesValidationErrors from 'laravel-nova/src/mixins/HandlesValidationErrors';
```
