### ISSUE TITLE
Repeatable fields

### ISSUE THREAD

**Issue by cerelli** [tightenco/nova-package-development#9]
Hello, I would like to create a package similar to this one, https://github.com/fourstacks/nova-repeatable-fields, but that goes to save the "repetable" fields in another table. 
Every time I save, it gives me an error saying that the attribute of the resource does not exist.
How can I create a field that is not a resource attribute?

**Comment by robmpreston** [comment]
@cerelli Can you give us more details and the code you have currently?

You're going to need to modify or create your own field, nova-repeatable-fields won't do what you want.

**Comment by julianpoma** [comment]
I also have the same request. This is what we are looking for:

Assume you want to create an Invoice. Each invoice has some data, stored on the `invoices_table`, and many "items" or "lines", stored on another `invoice_items_table`

When you create and invoice, you fill all the invoice data, but we would like to create several items at the same time, just like with the [package](https://github.com/fourstacks/nova-repeatable-fields). But in this case, when saving, those items should be saved on its own table:

**Invoice Model**
```
public function invoiceItems()
{
   return $this->hasMany(\App\InvoiceItems::class);
}
```

**Invoice Controller**
```
$invoice = \App\Invoice::create([$request->all()]);

...

foreach($request->invoice_items as $item) {
   $invoice->invoicesItems()->create([
      'description' => $item['desc'],
      'price' => $item['price']
   ]);
}
```

We already discussed this [here](https://github.com/fourstacks/nova-repeatable-fields/issues/2), and the author said he will prob take a look. 

Hope its clear and thanks!

**Comment by cerelli** [comment]
I modify the nova-repeatable-fields. 
This field return a json in fillAttributeFromRequest. I have a lead resource and in in lead model:
```
    public function notes()
    {
        return $this->hasMany('App\Note');
    }
```
This is my test in fillAttributeFromRequest of repeator.
```
    protected function fillAttributeFromRequest(NovaRequest $request,
                                                $requestAttribute,
                                                $model,
                                                $attribute)
    {
        $class = get_class($model);
        $arr = json_decode($request[$requestAttribute], true);
        $notes = new \App\Note;
        $notes->fill($arr);
        dd($class, $requestAttribute, $arr, $notes);
        if ($request->exists($requestAttribute)) {
            $notes = [
                    ['title' => 'Titolo 1','user_id' => 1,'priority' => 'Medium','body'=>'aa'],
                    ['title' => 'Titolo 2','user_id' => 1,'priority' => 'Low','body'=>'bbbbb']
                ];
            $model->$requestAttribute()->createMany($request[$requestAttribute]);
            // $model->{$attribute} = json_decode($request[$requestAttribute]);
            // dump($model->{$attribute} );
        }
    }
```
How can i save hasMany relation ? ` json_decode($request[$requestAttribute], true);`

**Comment by dillingham** [comment]
If this feature request, https://github.com/64robots/nova-row/issues/3, is accepted.. you'd be able to do that with this package
